### PR TITLE
revise gopkg.in version

### PR DESCRIPTION
**Pull request by rana**
import "gopkg.in/rana/ora.v3"

### CODE REVIEW

**Comment by tgulacsi** [comment]
Then we should have a "v3" branch with it, to let gopkg.in find it!

**Comment by rana** [comment]
doing it right now :)

**Comment by rana** [comment]
import "gopkg.in/rana/ora.v3" is causing build failures on windows. Not sure how to fix it other than remove it for now.

**Comment by rana** [comment]
will do!

**Comment by tgulacsi** [comment]
If you check out yout code under %GOPATH%/src/gopkg.in/rana/ora.v3 than it
shall work.

---
https://onename.com/tgulacsi

2015-08-30 23:02 GMT+02:00 Rana Ian <notifications@github.com>:

**Comment by rana** [comment]
when you check it out there is that where you do your ora code changes and
pull requests?

**Comment by tgulacsi** [comment]
Yes. That's just a directory name, does not have to match the git remote
origin.

---
https://onename.com/tgulacsi

2015-08-30 23:08 GMT+02:00 Rana Ian <notifications@github.com>:

**Pull request merged**
