### PR TITLE
return nil for all types instead of empty values

### LINKED ISSUE #105: Nill types
I have structure
```go
type A struct {
   Count *int
  Name *string
}
```
I'm using `ora` with `database/sql`.
When I'm executing and scanning (via sqlx) `select null as count, null as name from dual` I'm receiving `count=0`, `name=''`.
How to receive nils? Thanks.

### PR DESCRIPTION
**Pull request by goloveychuk**
this resolves #105 , but I can't run testing

### CODE REVIEW

**Comment by tgulacsi** [comment]
```
--- FAIL: TestSelectNullString_db (0.00s)
        z_db_test.go:75: Scan: sql: Scan error on column index 0: unsupported Scan, storing driver.Value type <nil> into type *string
--- FAIL: TestSetDriverName (0.03s)
        z_oracle_test.go:3500: sql: Scan error on column index 2: unsupported Scan, storing driver.Value type <nil> into type *string
```

**Comment by goloveychuk** [comment]
https://monosnap.com/file/l63tD0OCnU0cl6VhKVSH3PA2setOCC.png
really, don't know why :)
so in 66 line it should be `var s *string` to work properly.

Also this is huge breaking change, so even if it will be merged, it should tag with other version (4)

**Comment by goloveychuk** [comment]
ok, there are no difference between empty string and null in oracle. So maybe for string we should return "".  But there is a one between 0 and nil. So for numbers it should be nil

**Comment by goloveychuk** [comment]
forcepushed with "" for string

**Comment by tgulacsi** [comment]
Could you try "pr106" branch, please?

**Comment by goloveychuk** [comment]
@tgulacsi I'm already using the same code (except tests), with nulls for all types except string. It works good for my purposes.

**Comment by goloveychuk** [comment]
"" for string not very crucial, but when I'm making outerjoin and receiving 0 for id, it's very bad :)

**Comment by tgulacsi** [comment]
Thanks, then I'll merge that.

**Pull request closed without merging**
