### PR TITLE
Fixed fetching session timezone.

### PR DESCRIPTION
**Pull request by NOX73**

### CODE REVIEW

**Comment by tgulacsi** [comment]
Sorry, but why is this change needed? 
How does it fail, and how does it improve upon it?

Where is the test that fails without this fix, and succeeds with it?
If we don't have such test, then please include a new one!

**Comment by NOX73** [comment]
It fails with "unable to retrieve database timezone" here: https://github.com/rana/ora/blob/master/ses.go#L692

So the type assertion can't be done and it fails. It works properly with these fixes. I can try to write a test, but it's a bit difficult in this repo to setup a testing environment.

**Comment by tgulacsi** [comment]
It is quite strange to me... This does not happen on Linux with InstantClient 11.2 or Oracle XE 12 connecting to Oracle 11g - I cannot reproduce it.

But I've added a type switch on master - please try it!

**Comment by NOX73** [comment]
I use `oracle-instantclient12.1` and Oracle 11.2

**Pull request closed without merging**
